### ISSUE TITLE
gunicorn config log格式錯誤

### ISSUE THREAD

**Issue by takidog** [JohnSounder/AP-API#78]
`src/gunicorn_cfg.py`
```python
access_logformat = "[api.v2] %(h)s %(l)s %(u)s %(t)s .%(r)s. %(s)s %(b)s .%(f)s. .%(a)s. conn=\"%({Connection}i)s\""
```

gunicorn 正確的log format是
```
access_log_format
```

用log統計資料會較為不便

**Comment by abc873693** [comment]
有相關資料可以作為參考？
沒有明確資料佐證是正確log

**Comment by takidog** [comment]
v2的log 很明顯沒有照著這個格式輸出
v2 log

92.168.240.3 - 1105103222 [03/Jul/2019:03:31:08 +0800] \"GET /v2/ap/users/scores/107/2 HTTP/1.1\" 200 495 \"-\" \"Dart/2.3 (dart:io)

現行v3 log

[08/Sep/2019:11:05:45 +0000] [api.v3] [172.19.0.3] [PostmanRuntime/7.16.3]   [POST] [/oauth/token] [200] 

(從docker撈可能有些雜，手機排版)

**Comment by abc873693** [comment]
我覺得可能是之前學長需要有他們需要的資料才這樣定義
裡面也會記錄學號
v3有打算移除?

**Comment by takidog** [comment]
> 我覺得可能是之前學長需要有他們需要的資料才這樣定義
> 裡面也會記錄學號
> v3有打算移除?

v3沒有辦法從gunicorn這一層去紀錄(JWT auth )
v2走http basic auth 才可以的樣子

之前是定義了 但是變數命名錯誤  gunicorn並沒有使用到定義的資料

v2 的format 中有存在 "[api.v2] " 在log並沒有出現
我在測試中將那行刪除也並沒有改變log的輸出，可以確定沒有吃到那行設定

**Comment by abc873693** [comment]
如果目前v2不影響 
這個問題就移動至v3處理
就先把它關閉了
